// 本模块集中导出文档内核的原子源码补丁能力。

export * from './sourcePatches.ts'
export * from './assetContentPatches.ts'
export * from './assetReferencePatches.ts'
export * from './tableStructurePatches.ts'
export * from './managedNodeRuleRemovalPatches.ts'
export * from './inlineStylePatches.ts'
export * from './componentVisibilityPatches.ts'
export * from './componentTagPatches.ts'
export * from './componentRemovalPatches.ts'
export * from './componentMovePatches.ts'
export * from './componentInsertionPatches.ts'
export * from './publicComponentInsertionPatches.ts'
export * from './publicComponentInstancePatches.ts'
export * from './publicComponentLocalizationPatches.ts'
export * from './opaqueElementAdoptionPatches.ts'
export * from './themeTokenPatches.ts'
export * from './linkPatches.ts'
export * from './managedRulePatches.ts'
export * from './managedRuleTarget.ts'
export * from './textContentPatches.ts'
export * from './textRangePatches.ts'
export * from './textStructurePatches.ts'
